name: CI/CD Pipeline

on:
  push:
    branches:
      - Main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build backend
        run: |
          docker build -t back-end ./Back-end

      - name: Build frontend
        run: |
          docker build -t front-end ./Front-end

      - name: Build nginx
        run: |
          docker build -t nginx .
          
  deploy:
    runs-on: self-hosted
    steps:
          - name: deploying
            run: |
              cd /home/ubuntu/project
              docker-compose up -d
