name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Backend Docker Image
        working-directory: Back-end
        run: docker build -t backend .

      - name: Build Frontend Docker Image
        working-directory: Front-end
        run: docker build -t frontend .

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: CloudHubProject

