name: CI/CD Pipeline

on:
  push:
    branches:
      - Main
env:
  AZURE_WEBAPP_NAME: CloudHubProject
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  
jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Backend Docker Image
        working-directory: Back-end
        run: docker build -t backend .

  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Frontend Docker Image
        working-directory: Front-end
        run: docker build -t frontend .

  deploy:
    runs-on: ubuntu-latest
    needs: [build_backend, build_frontend]
    steps:
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
