name: CI/CD Pipeline

on:
  push:
    branches:
      - Main

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Build Backend Docker Image
        working-directory: Back-end
        run: docker build -t backend .

  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Build Frontend Docker Image
        working-directory: Front-end
        run: docker build -t frontend .

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: CloudHubProject
