name: CI/CD Pipeline

on:
  push:
    branches:
      - Main

    steps:
      - name: Build Backend Docker Image
        working-directory: backend
        run: docker build -t backend .

    steps:
      - name: Build Frontend Docker Image
        working-directory: frontend
        run: docker build -t frontend .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: CloudHubProject
