name: CI/CD Pipeline

on:
  push:
    branches:
      - Main

env:
  AZURE_WEBAPP_NAME: CloudHubProject

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build backend
        run: |
          docker build -t back-end ./Back-end

      - name: Build frontend
        run: |
          docker build -t front-end ./Front-end

      - name: Build nginx
        run: |
          docker build -t nginx .
          
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Virtual Machine
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i <(echo "$SSH_PRIVATE_KEY") samuel.rak@kosickaakademia.sk "cd /Home/ubuntu && git pull && docker-compose up -d"
